README.md
Updates the product description in the README
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> chore: update product description in readme

.github/PULL_REQUEST_TEMPLATE.md, Tests/FaceLivenessTests/LivenessTests.swift, Tests/FaceLivenessTests/MockFaceDetectionResultHandler.swift, Tests/FaceLivenessTests/MockFaceDetector.swift, Tests/FaceLivenessTests/MockLivenessService.swift
This PR consists of two small chores:
1. The addition of the PULL_REQUEST_TEMPLATE.md
2. Simple assertions on test interactions between `LivenessCaptureSession`/`FaceLivenessDetectionViewModel` and `MockFaceDetector` and `MockLivenessService`.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> PULL_REQUEST_TEMPLATE.md  and interactions illustration

HostApp/HostApp.xcodeproj/project.pbxproj, HostApp/HostApp/AmplifyConfiguration/amplifyconfiguration.json, HostApp/README.md
* Adding placeholder amplifyconfiguration.json to project
* Add README.md for setting up and running host app
=> chore: add README.md to HostApp

.github/workflows/liveness_unit_tests.yml
Adds GitHub Action to trigger unit test workflow on PRs and merges to main.
=> chore: add unit tests workflow

Sources/FaceLiveness/Utilities/UserAgent.swift
=> chore: update user agent string with correct library version

HostApp/HostApp.xcodeproj/project.pbxproj, Package.swift, Sources/FaceLiveness/Utilities/UserAgent.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift
* update liveness fit timeout to be configurable from the backend service
* update amplify swift version dependency
* update library versioning
=> chore: refactor session fit timeout from backend service

HostApp/HostApp/Views/LivenessCheckErrorContentView.swift, Sources/FaceLiveness/Resources/Base.lproj/Localizable.strings, Sources/FaceLiveness/Utilities/LocalizedStringKey+Liveness.swift, Tests/FaceLivenessTests/LivenessTests.swift, Tests/IntegrationTestApp/IntegrationTestApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Tests/IntegrationTestApp/IntegrationTestApp/Views/LivenessCheckErrorContentView.swift
* Updating the face fit instruction text and remove references to time out duration
* Updating error messages in host app and integration app and remove references to time out duration
=> chore: update face fit instruction text and error message

.github/workflows/deploy_liveness.yml, .github/workflows/deploy_release.yml, .github/workflows/deploy_unstable.yml
=> chore: fix release workflow

.github/workflows/liveness_unit_tests.yml
=> chore: make unit test GH action reusable

.github/workflows/liveness_unit_tests.yml
=> chore: fix unit test GH action

Sources/FaceLiveness/FaceDetection/BlazeFace/DetectedFace.swift, Tests/FaceLivenessTests/DetectedFaceTests.swift
Fix incorrect magic number for calculating face height
=> chore: update magic number for face height

Sources/FaceLiveness/Resources/Base.lproj/Localizable.strings
Add default empty string value for a blank string
=> chore: add empty string value for string localization

HostApp/HostApp/Views/LivenessResultContentView.swift, HostApp/HostApp/Views/LivenessResultView.swift, Sources/FaceLiveness/Resources/Base.lproj/Localizable.strings
* Update sample host app results view to be the same as Android's Liveness result view
* Update photosensitivity warning description to refer to "different colors"
=> chore: minor UX updates in sample host app

Tests/IntegrationTestApp/IntegrationTestAppUITests/LivenessIntegrationUITests.swift, Tests/IntegrationTestApp/IntegrationTestAppUITests/UIConstants.swift
* Update existing UI integration test based on latest UX updates in current released version
=> chore: update integration test to match latest UX updates

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/workflows/feature_request.yml, .github/workflows/issue_closed.yml, .github/workflows/issue_comment.yml, .github/workflows/issue_opened.yml, .github/workflows/notify_release.yml
* Adding templates for new issues and feature request
* Add GH actions to automate Slack notifications to when issues are open, closed, and commented and when a release is completed
=> chore: add GH workflows and templates

HostApp/HostApp/Views/StartSessionView.swift, HostApp/HostApp/Views/StartSessionViewModel.swift
* Add error handling to create session request
=> chore: add error handling to create session in sample app

Sources/FaceLiveness/Views/Liveness/LivenessViewController.swift
* Update preview layer to be optional and add guards/checks to prevent NPEs
=> fix: update preview layer to be optional and check for nil values

Package.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/126
Update Amplify Swift dependency to 2.29.1 to pull in the latest privacy manifest support files.
=> chore: Update Amplify Swift dependency

HostApp/HostApp.xcodeproj/project.pbxproj, HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, HostApp/HostApp/Views/ExampleLivenessView.swift, Package.resolved, Package.swift, Sources/FaceLiveness/FaceDetection/BlazeFace/DetectedFace.swift, Sources/FaceLiveness/FaceDetection/BlazeFace/FaceDetectorShortRange+Model.swift, Sources/FaceLiveness/FaceDetection/FaceDetector.swift, Sources/FaceLiveness/Views/GetReadyPage/GetReadyPageView.swift, Sources/FaceLiveness/Views/Instruction/InstructionContainerView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+VideoSegmentProcessor.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessViewControllerPresenter.swift, Sources/FaceLiveness/Views/Liveness/LivenessStateMachine.swift, Sources/FaceLiveness/Views/Liveness/LivenessViewController.swift, Sources/FaceLiveness/Views/LoadingPage/LoadingPageView.swift, Tests/FaceLivenessTests/DetectedFaceTests.swift, Tests/FaceLivenessTests/LivenessTests.swift, Tests/FaceLivenessTests/MockLivenessService.swift
None
Add changes no light challenge support and dynamic configuration for face matching
=> feat: add no light challenge implementation

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
None
Update `amplify-swift` dependency to `2.33.3`
=> chore: update amplify dependency

.github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/liveness_unit_tests.yml
=> chore: update codecov version and add token

Package.swift
=> chore: update to latest Amplify Swift dependency

.github/workflows/release_kickoff.yml
None
Update `macos` version of release runner
=> chore: update macos release runner

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
None
Update amplify dependency to pull in fix PR https://github.com/aws-amplify/amplify-swift/pull/3965
=> chore: update amplify dependency to 2.46.1
