Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Tests/FaceLivenessTests/CredentialsProviderTestCase.swift, Tests/FaceLivenessTests/MockAWSCredentials.swift, Tests/FaceLivenessTests/MockAWSTemporaryCredentials.swift, Tests/FaceLivenessTests/MockCredentialsProvider.swift
Passes a caller provided credentials provider down to the session creation.
=> fix: pass provided credentialsprovider to session

Sources/FaceLiveness/Resources/Base.lproj/Localizable.strings
Fixes typo in Localizable.strings that presented the key rather than the value on screen.
=> fix: typo in localizable.strings

Package.resolved, Package.swift, Sources/FaceLiveness/Utilities/UserAgent.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionError.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Tests/FaceLivenessTests/MockLivenessService.swift
Updates to Amplify Swift >= v2.11.0 to allow for better service error propagation.
=> fix: service exception handling

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/FaceLiveness/Resources/Base.lproj/Localizable.strings, Sources/FaceLiveness/Utilities/LocalizedStringKey+Liveness.swift, Sources/FaceLiveness/Views/GetReadyPage/OvalIllustrationExamples.swift, Sources/FaceLiveness/Views/GetReadyPage/OvalIllustrationView.swift, Sources/FaceLiveness/Views/RecordingButton.swift
=> fix: add missing localization string resources

Package.resolved, Package.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Tests/FaceLivenessTests/MockLivenessService.swift
Sends websocket close frame in the case of a client side timeout of face in oval matching.
=> fix: send client close frame

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Tests/FaceLivenessTests/LivenessTests.swift
* Change no match timeout duration check from frames per seconds to elapsed time interval so that timeout is not longer than 7 seconds.
=> fix: update no match timeout check from frame count to elapsed time

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Sources/FaceLiveness/Views/Liveness/LivenessStateMachine.swift, Tests/FaceLivenessTests/LivenessTests.swift
* update web socket close to include liveness-specific close code
* update timeout logic start the timeout timer when the oval is initially displayed to handle edge case when a face is detected and the oval is displayed and the user moves away immediately
=> chore: provide more fine-grained websocket close code on errors

.github/workflows/deploy_liveness.yml
=> chore: clean up github actions

.github/workflows/liveness_unit_tests.yml
* fix unit test GitHub action workflow
=> test: fix unit test GitHub action workflow

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Tests/FaceLivenessTests/LivenessTests.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/61
* Dispatch session time out error to be async to unblock component completion handler
=> fix: update session timed out error to be non-blocking

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/61
* Reset the session timeout time so that duplicate errors are being sent once in error state
=> fix: duplicate session timeout error messages

Sources/FaceLiveness/FaceDetection/BlazeFace/DetectedFace.swift, Sources/FaceLiveness/FaceDetection/BlazeFace/FaceDetectorShortRange+Model.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Tests/FaceLivenessTests/DetectedFaceTests.swift, Tests/FaceLivenessTests/LivenessTests.swift
* update the bounding box from landmark calculation based on new algorithm provided by the Rekognition science team.
See similar PR from Liveness JS: https://github.com/aws-amplify/amplify-ui/pull/4685
For reference, documented algorithm in JS
```js
function generateFaceLandamrks(faces, oval_box)
const keypoints = faces[0].keypoints;
const face_box_bottom = faces[0].box.yMax;
const leftEye  =  keypoints[1];
const rightEye =  keypoints[0];
const nose    =  keypoints[2];
const leftEar =  keypoints[5];
const rightEar =  keypoints[4];
const ovalHeight = oval_box.yMax- oval_box.yMin;
const ovalTop = oval_box.yMin;
const eyeCenter = [];
eyeCenter[0] = (leftEye[0] + rightEye[0]) / 2;
eyeCenter[1] = (leftEye[1] + rightEye[1]) / 2;
const { …
```
=> chore: update face bounding box landmark calculations

Sources/FaceLiveness/AV/VideoChunker.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+VideoSegmentProcessor.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift
* update video segment processor to send the final event at a delayed time interval after the video chunk.  Sending the final video event immediately after the video chunk causes the backend service to queue the final event and results in additional processing latency
=> fix: send the final video event at a delayed time interval

Sources/FaceLiveness/AV/LivenessCaptureSession.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/LivenessViewController.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/68
Root cause: 
If the liveness check screen and open and dismissed quickly several times, it's possible to run into a race condition wherein the `AVCaptureSession.startRunning()` while it is being configured which results in the following error
```
'NSGenericException', reason: '*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration'
```
Resolution: 
* Start the AVCaptureSession in a queue that has a higher QoS
* Add additional code to cleanup and dispose of the AVCaptureVideoPreviewLayer and its associate AVCaptureSession
* In Flutter app, depending on the integration, it's possible to dismiss the …
=> fix: resolve race condition when starting AVCaptureSession

Sources/FaceLiveness/AV/LivenessCaptureSession.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewView.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewViewModel.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/98
* Make sure to stop the camera session in the preview screen so that the camera session doesn't continue to run
=> fix: cleanup camera session in the preview page

Sources/FaceLiveness/AV/LivenessCaptureSession.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/103
* Ensure that the video setting for the AVCaptureSession is mirrored.  There was previous code that manually rotated and mirrored the images and was removed in favor of setting the video session to be portrait.  This [code](https://github.com/aws-amplify/amplify-ui-swift-liveness/pull/91) change missed setting it video output to mirror.
=> fix: ensure video image is mirrored

Sources/FaceLiveness/AV/VideoChunker.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/99
* Prevent crash in `AVAssetWriter.finishWriting` if the AVAssetWriter has already finished
* Tested manually to verify the method is not called once the state is completed.
=> fix: add additional guard for finishing AVAssetWriter

HostApp/HostApp.xcodeproj/project.pbxproj, HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
None
Update and pin `amplify-swift` dependency to 2.27.2
=> chore: update amplify-swift dependency to 2.27.2

HostApp/HostApp.xcodeproj/project.pbxproj, HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Sources/FaceLiveness/AV/LivenessCaptureSession.swift
Some customers are experiencing crashes with following log:
`SIGABRT: *** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration `
- Use `.userInteractive` priority for task queue for `AVCaptureSession`
- [Not related to the fix] Update `HostApp` to consume local ancestor `amplify-ui-swift-liveness` repo
=> fix: use higher priority task queue for AVCaptureSession

Sources/FaceLiveness/AV/LivenessCaptureSession.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewViewModel.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Sources/FaceLiveness/Views/Liveness/LivenessViewController.swift
* Update the logic for configuring and starting the AVCaptureSession so that starting the session is deferred after the session is configured to avoid AVCaptureSession crash as a result of in progress configuration of session.
=> fix: prevent AVCaptureSession from starting during session configuration

HostApp/HostApp/Views/ExampleLivenessView.swift, HostApp/HostApp/Views/LivenessCheckErrorContentView.swift, Package.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionError.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Tests/IntegrationTestApp/IntegrationTestApp/Extension/MockLivenessCaptureSession.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/114
* Add support for invalid signature exception from service so that the exception is returned to caller instead of defaulting to unknown exception.  This also required updating to the latest Amplify Swift library version [2.29.3](https://github.com/aws-amplify/amplify-swift/releases/tag/2.29.3).
* Update oval fit timeout exception to return as `faceInOvalMatchExceededTimeLimitError` with more descriptive error message
* Fix build error in MockLivenessCaptureSession as a result of previous changes to LivenessCaptureSession (#124)
By submitting this pull request, I confirm that my contribution is made under the terms of …
=> chore: improve error messages

Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewOutputSampleBufferDelegate.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewViewModel.swift
https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/129
* Refactor and remove strong reference retain cycle between `CameraPreviewViewModel` and `LivenessCaptureSession`
* Tested and verified that strong reference doesn't exists when viewed in Xcode's memory graph
=> fix: remove strong reference retain cycle from camera preview view model

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, HostApp/HostApp/Model/LivenessResult.swift, HostApp/HostApp/Views/ExampleLivenessView.swift, HostApp/HostApp/Views/LivenessResultContentView+Result.swift, HostApp/HostApp/Views/LivenessResultContentView.swift, Package.resolved, Package.swift, Sources/FaceLiveness/Views/GetReadyPage/GetReadyPageView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Tests/FaceLivenessTests/CredentialsProviderTestCase.swift, Tests/FaceLivenessTests/LivenessTests.swift, Tests/FaceLivenessTests/MockLivenessService.swift
Add attempt count changes and update UI for result view in HostApp
=> chore: Add attempt count changes

.github/workflows/deploy_liveness.yml
Unstable release GH action failing: https://github.com/aws-amplify/amplify-ui-swift-liveness/actions/runs/8974137653
Update ruby version to `1.171.0`
~~- [ ] Added new tests to cover change, if needed~~
~~- [ ] Build succeeds with all target using Swift Package Manager~~
~~- [ ] All unit tests pass~~
~~- [ ] Security oriented best practices and standards are followed (e.g. using input sanitization, principle of least privilege, etc)~~
~~- [ ] Documentation update for the change if required~~
~~- [ ] If breaking change, documentation/changelog update with migration instructions~~
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
=> chore: update ruby version to fix CI deployments

Sources/FaceLiveness/Views/GetReadyPage/ImageFrameView.swift
This PR fixes the video feed not being mirrored in the "Get Ready" view. This was happening because the video **was** mirrored, but the Image displayed on this screen was being mirrored **again**.
=> fix: Fixing video not being mirrored in the 'Get Ready' screen

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift
None
- Add error handling on Loading View
- Resolve below compiler warning:
`Accessing StateObject's object without being installed on a View. This will create a new instance each time.`
=> fix: handle error on loading view

HostApp/HostApp.xcodeproj/project.pbxproj, Sources/FaceLiveness/Views/Liveness/LivenessViewController.swift
The `_LivenessViewController` currently centers its camera frame only when its view is loaded, but not when its subviews are laid out. 
This causes the video feed to appear off-centered when the `FaceLivenessDetectorView` is stacked with other components (i.e. headers, navigation bars, etc), or when used in a `UIHostingController`.
This PR fixes this issue by re-centering the camera frame on `viewDidLayoutSubviews()`. 
---
I'm also removing the liveness package being unnecessary copied as a resource for the example HostApp
---
=> fix: Updating the camera frame position when the subviews are laid out

Sources/FaceLiveness/AV/VideoChunker.swift
**Issue #, if available:**
- https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/148
This PR attempts to fix an `NSInternalInconsistencyException` crash that might be happening when calling `AVAssetWriter.finishWriting` on an instance that is already `completed`.
There was a previous validation in place that checked if `state != .complete`, but `state` is a local variable that is not really tracking the write's state, so I decided to replace it with `AVAssetWriter.status`.
=> fix: Fixing a crash when attempting to call finishWriting

HostApp/HostApp/Views/ExampleLivenessView.swift, HostApp/HostApp/Views/LivenessCheckErrorContentView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionError.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Sources/FaceLiveness/Views/Liveness/LivenessStateMachine.swift
This PR adds `FaceLivenessDetectionError.cameraNotAvailable`, which is reported when there's a problem accessing the camera that is **not** caused by lack of user permissions.
The underlying websocket close code for this error remains `4006`, as per the contract with the Rekognition service.
-   TBA
=> feat(FaceLivenessDetectionError): Adding new `.cameraNotAvailable` error.

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift
**Issue #, if available:**
- https://github.com/aws-amplify/amplify-ui-swift-liveness/issues/166
This PR maps the internal `LivenessError.viewResignation` error to the public `FaceLivenessDetectionError.userCancelled`, so that we report that one when the user sends the app to the background during a liveness check.
=> fix: Returning .userCancelled when the app goes to the background during a Liveness check.

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, HostApp/HostApp/Views/ExampleLivenessView.swift, Package.resolved, Package.swift
None
Update `amplify-swift` dependency to 2.38.0 for clock skew support
https://github.com/aws-amplify/amplify-swift/releases/tag/2.38.0
=> chore: update Amplify dependency to 2.38.0 for clock skew support

HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Package.resolved, Package.swift
None
Update Amplify Swift dependency to 2.42.1
=> chore: update amplify swift dependency to 2.42.1

.github/composite_actions/run_xcodebuild/action.yml, .github/composite_actions/run_xcodebuild_test/action.yml, .github/workflows/build_liveness.yml, .github/workflows/liveness_unit_tests.yml, HostApp/HostApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, HostApp/HostApp/HostAppApp.swift, HostApp/HostApp/Views/ExampleLivenessView.swift, Package.resolved, Package.swift
None
Update Amplify dependency to 2.45.4
=> chore: update amplify dependency to 2.45.4

HostApp/HostApp.xcodeproj/project.pbxproj, HostApp/HostApp/Views/ExampleLivenessView.swift, HostApp/HostApp/Views/ExampleLivenessViewModel.swift, HostApp/HostApp/Views/RootView.swift, HostApp/HostApp/Views/StartSessionView.swift, Sources/FaceLiveness/AV/LivenessCaptureDevice.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewView.swift, Sources/FaceLiveness/Views/GetReadyPage/CameraPreviewViewModel.swift, Sources/FaceLiveness/Views/GetReadyPage/GetReadyPageView.swift, Sources/FaceLiveness/Views/Instruction/InstructionContainerView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionError.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel+FaceDetectionResultHandler.swift, Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionViewModel.swift, Sources/FaceLiveness/Views/Liveness/LivenessStateMachine.swift, Tests/FaceLivenessTests/CredentialsProviderTestCase.swift, Tests/FaceLivenessTests/LivenessTests.swift
None
Back camera support for no light challenge
=> feat: add back camera support

Sources/FaceLiveness/Views/Liveness/FaceLivenessDetectionView.swift
None
Build fix for missing default initializer for `challengeOptions`
=> chore(build): add default init for ChallengeOptions
